"""Shared Basketball Reference constants."""

from __future__ import annotations

MIN_GAMES = 20

# Historical BRef team codes -> modern franchise abbreviations
TEAM_ABBR_MAP: dict[str, str] = {
    "PHW": "GSW",
    "SFW": "GSW",
    "GSW": "GSW",
    "FTW": "DET",
    "DLC": "LAL",
    "LAL": "LAL",
    "MIN": "MIN",
    "MLH": "ATL",
    "STL": "ATL",
    "ATL": "ATL",
    "SDR": "HOU",
    "HOU": "HOU",
    "CAP": "WAS",
    "WSB": "WAS",
    "WAS": "WAS",
    "KCK": "SAC",
    "KCO": "SAC",
    "CIN": "SAC",
    "ROC": "SAC",
    "SAC": "SAC",
    "SDC": "LAC",
    "LAC": "LAC",
    "BUF": "LAC",
    "NOJ": "UTA",
    "UTA": "UTA",
    "SEA": "OKC",
    "OKC": "OKC",
    "CHH": "CHA",
    "CHA": "CHA",
    "NJN": "BKN",
    "BKN": "BKN",
    "NOH": "NOP",
    "NOK": "NOP",
    "NOP": "NOP",
    "VAN": "MEM",
    "MEM": "MEM",
    "PHO": "PHX",
    "PHX": "PHX",
    "BRK": "BKN",
    "CHS": "CHI",
    "CHI": "CHI",
    "BOS": "BOS",
    "NYK": "NYK",
    "DET": "DET",
    "CLE": "CLE",
    "MIL": "MIL",
    "POR": "POR",
    "SAS": "SAS",
    "DEN": "DEN",
    "IND": "IND",
    "ORL": "ORL",
    "MIA": "MIA",
    "DAL": "DAL",
    "TOR": "TOR",
}
